### ISSUE TITLE
Font family is not applied after the page is refreshed

### ISSUE THREAD

**Issue by handhikadj** [silexlabs/grapesjs-fonts#12]
the font family is set, but it's not applied to the element after the page is refreshed

Steps to reproduce:

1. go to the demo site: https://codepen.io/lexoyo/pen/zYLWdxY
2. install a font(s)
3. apply the installed font family on selected element on Typography section from Style Manager within the sidebar
4. refresh the page and see the element on the canvas

I also experience this issue on my personal project with the remote storage

**Comment by lexoyo** [comment]
Hello

I just tried on the demo site and it works for me, here is the data stored in the local storage

```
{
  "assets": [
  ],
  "styles": [
  ],
  "pages": [
  ],
  "fonts": [
    {
      "name": "ABeeZee",
      "value": "\"ABeeZee\", sans-serif",
      "variants": []
    }
  ]
}
```

Would you please

1. confirm you hit "save" and not just close the popin
2. what is your browser (i'm with firefox beacause it's foss)

**Comment by handhikadj** [comment]
@lexoyo did you try to change the font family of the element?
on mine, after I installed Comic Neue, change it to the font, and refresh the page, still doesn't work

<img width="854" alt="img" src="https://github.com/silexlabs/grapesjs-fonts/assets/22522638/e1f0cd88-d0e6-42fb-859e-91808bb2d3bf">

**Comment by mapildain** [comment]
I am having the same problem, also when I publish the web page the font is not displayed :(

**Comment by lexoyo** [comment]
What's your browser pls

I need to reproduce...

**Comment by handhikadj** [comment]
Chrome Version 121.0.6167.85

**Comment by lexoyo** [comment]
Would you try with Firefox pls?

**Comment by systemfreaks** [comment]
firefox has the same issue

**Comment by lexoyo** [comment]
Really?! I can't reproduce :'(
And this plugin is in use in silex and it works there, so crazy
I'll try again

**Comment by lexoyo** [comment]
Would you please describe step by step what you are doing pls? Maybe i'm missing something small

**Comment by systemfreaks** [comment]
https://www.loom.com/share/830fef94ab5f46bbbb426ade157a1715](https://www.loom.com/share/830fef94ab5f46bbbb426ade157a1715 here check this  video

**Comment by lexoyo** [comment]
Thank you @systemfreaks 
Unfortunately the link gives a 404

**Comment by lexoyo** [comment]
oh no ok, i found it, looking at it right now

**Comment by lexoyo** [comment]
it's crazy, i really tried to reproduce and it works on chrom and firefox for me
i'm on linux, maybe that's why? or an extension you have
would you share the value in the local storage for me? to see if the problem is saving or loading

**Comment by systemfreaks** [comment]
Unfortunatelly, the file is too long to share, the font appears in local storage and it seems that it doesn't;t load, if you do save again it does load the font

**Comment by lexoyo** [comment]
so if you save twice it works?
can you check in the local storage if the font is there?
also check what's loading in the network panel pls
