### ISSUE TITLE
Base Google Fonts API URL problem

### ISSUE THREAD

**Issue by acasmp** [silexlabs/grapesjs-fonts#15]
First time using it, but when I try to launch the dialog with editor.current.runCommand('open-fonts') I get a bunch of network resource errors. From checking the logs, it seems the problem is that the call is being made to https://fonts.googleapis.com  instead of https://www.googleapis.com, which as of today seems to be the way to call it.

I can send a PR if the issue is confirmed but maybe I'm missing something? Also sending base_url as an option didn't seem to work either.

Other than that the plugin looks great. Thanks!

**Comment by lexoyo** [comment]
Hello
I believe it's fonts.googleapis.com isn't it?
Also you have an option to change that: https://github.com/silexlabs/grapesjs-fonts?tab=readme-ov-file#options
(i already had problems with this URL, i'm don't remember why)

**Comment by lexoyo** [comment]
ok i understand now, it was also bugged on v3.silex.me

now it should be fixed with the default values for google servers

i made 2 different URLs for the font server (`https://fonts.googleapis.com`) and the font API ( `https://www.googleapis.com`) used to get the fonts list
