### ISSUE TITLE
Global Font

### ISSUE THREAD

**Issue by gxanshu** [silexlabs/grapesjs-fonts#7]
no doubt man, this plugin is really awesome it helps a lot. thank you very much for your work. but i have a simple issue or a question to ask how can i use that font globally. let suppose i opened the font dialog and select `roboto` font then it will appear in the font-family section of typography in style manager and then we manually select text element and change there font to `roboto`.

now what is want to do here is to add roboto font and then it will automatically added to all the texts globally. like in CSS we do

```css
* {
font-family: 'roboto';
 }

**Comment by aianshume** [comment]
well now i fixed that issue by edding `fonts.js` file now i have issue that there is no css file inside the plugin after installing this plugin i got an unstyled modal.

not like you show in the README
![image](https://user-images.githubusercontent.com/68537640/232370475-89ef656d-dba7-4c32-87b4-c6ea8c259138.png)

**Comment by lexoyo** [comment]
Hey @gxanshu 
I'm so sorry I didn't see your issue
Is it still an issue ? What did you change in fonts.js?

**Comment by gxanshu** [comment]
I would like to add two features to this package:

1. The ability to use a font globally.
2. The ability to use fonts that are installed on the user's computer instead of Google fonts.

I think it would not a good idea to make some changes for just my personal requirements so I just download the package and made the necessary changes to the code.

There are no immediate issues with the package as it is, but it would be helpful to add a global font option. Users would be able to enable this option in the `pluginOptions` and then use any font they want globally.

The modal in the photo does not have a design yet, so we need to fix that as well.

**Comment by lexoyo** [comment]
These are great ideas!

Use of a font globaly could be an option in the dialog. Like a checkbox "Default"

To enable the user custom fonts may be dangerous as visitors may see something different right? Maybe we could add the fonts which are vy default in grapesjs so that the user can choose to add them to the ui or not. Or you can contribute it as an option as you said. Going even further we could let the user upload fonts?

A basic design is hardcoded as an option (replaceable by the option) or is it a bug?

I would appreciate a PR for each of these! Especially the first point

**Comment by lexoyo** [comment]
Note that in the PR it is important to split 1 PR per feature :))

**Comment by gxanshu** [comment]
i will add the default font should i make a PR ?

**Comment by lexoyo** [comment]
Yes please

**Comment by gxanshu** [comment]
Ok

**Comment by lexoyo** [comment]
@gxanshu I'm sorry it took so long, you raised an issue and I had to understand what's the best way to do this

the problem with the "global font" approach  is that it doesn't  let the user choose  other global  fonts properties  such as  weight, color...

 so in the end we need to let the user style the body  with all the font properties, that's the approach I suggest

what do you think?

**Comment by gxanshu** [comment]
@lexoyo sorry to took so long but i'm currently inactive in GrapesJS development so i can't say which approach should you take. it would be nice if you close my PR. Then we will think about a good way to solve this issue.

**Comment by lexoyo** [comment]
Ok
Thank you for your understanding
